# Generated by Django 5.0.4 on 2024-07-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField()),
            ],
        ),
    ]
