# Generated by Django 5.0.4 on 2024-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0010_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la Société')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='Nom Responsable')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('address', models.TextField(verbose_name='Adresse')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
