# Generated by Django 5.0.4 on 2024-07-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0011_companyinfo_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
    ]
