# Generated by Django 5.0.4 on 2024-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0014_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
