# Generated by Django 5.0.6 on 2024-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0015_employee_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
